# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:15:52+00:00

from __future__ import annotations

from enum import Enum


class OutputSRS(Enum):
    integer_4326 = 4326
    integer_4269 = 4269
    integer_3005 = 3005
    integer_26907 = 26907
    integer_26908 = 26908
    integer_26909 = 26909
    integer_26910 = 26910
    integer_26911 = 26911


class Criteria(Enum):
    shortest = 'shortest'
    fastest = 'fastest'


class DistanceUnit(Enum):
    km = 'km'
    mi = 'mi'


class OutputFormat(Enum):
    json = 'json'
    kml = 'kml'
    html = 'html'


class OutputFormat4(Enum):
    json = 'json'
    html = 'html'


class OutputFormat6(Enum):
    json = 'json'
    kml = 'kml'
    html = 'html'


class OutputFormat16(Enum):
    json = 'json'
    html = 'html'


class OutputFormat18(Enum):
    json = 'json'
    kml = 'kml'
    html = 'html'
